const keys = [
  [
    {
      code: 'Backquote',
      type: 'Symbol',
      downEng: '`',
      upEng: '~',
      downRu: 'ё',
      upRu: 'Ё',
    },
    {
      code: 'Digit1',
      type: 'Symbol',
      downEng: '1',
      upEng: '!',
      downRu: '1',
      upRu: '!',
    },
    {
      code: 'Digit2',
      type: 'Symbol',
      downEng: '2',
      upEng: '@',
      downRu: '2',
      upRu: '"',
    },
    {
      code: 'Digit3',
      type: 'Symbol',
      downEng: '3',
      upEng: '#',
      downRu: '3',
      upRu: '№',
    },
    {
      code: 'Digit4',
      type: 'Symbol',
      downEng: '4',
      upEng: '$',
      downRu: '4',
      upRu: ';',
    },
    {
      code: 'Digit5',
      type: 'Symbol',
      downEng: '5',
      upEng: '%',
      downRu: '5',
      upRu: '%',
    },
    {
      code: 'Digit6',
      type: 'Symbol',
      downEng: '6',
      upEng: '^',
      downRu: '6',
      upRu: ':',
    },
    {
      code: 'Digit7',
      type: 'Symbol',
      downEng: '7',
      upEng: '&',
      upRu: '?',
      downRu: '7',
    },
    {
      code: 'Digit8',
      type: 'Symbol',
      downEng: '8',
      upEng: '*',
      downRu: '8',
      upRu: '*',
    },
    {
      code: 'Digit9',
      type: 'Symbol',
      downEng: '9',
      upEng: '(',
      downRu: '9',
      upRu: '(',
    },
    {
      code: 'Digit0',
      type: 'Symbol',
      downEng: '0',
      upEng: ')',
      downRu: '0',
      upRu: ')',
    },
    {
      code: 'Minus',
      type: 'Symbol',
      downEng: '-',
      upEng: '_',
      downRu: '-',
      upRu: '_',
    },
    {
      code: 'Equal',
      type: 'Symbol',
      downEng: '=',
      upEng: '+',
      downRu: '=',
      upRu: '+',
    },
    {
      code: 'Backspace',
      type: 'Function',
      down: 'Backspace',
      specialSize: 1,
    },
  ],
  [
    {
      code: 'Tab',
      type: 'Function',
      down: 'Tab',
    },
    {
      code: 'KeyQ',
      type: 'Symbol',
      downEng: 'q',
      downRu: 'й',
      letter: true,
    },
    {
      code: 'KeyW',
      type: 'Symbol',
      downEng: 'w',
      downRu: 'ц',
      letter: true,
    },
    {
      code: 'KeyE',
      type: 'Symbol',
      downEng: 'e',
      downRu: 'у',
      letter: true,
    },
    {
      code: 'KeyR',
      type: 'Symbol',
      downEng: 'r',
      downRu: 'к',
      letter: true,
    },
    {
      code: 'KeyT',
      type: 'Symbol',
      downEng: 't',
      downRu: 'е',
      letter: true,
    },
    {
      code: 'KeyY',
      type: 'Symbol',
      downEng: 'y',
      downRu: 'н',
      letter: true,
    },
    {
      code: 'KeyU',
      type: 'Symbol',
      downEng: 'u',
      downRu: 'г',
      letter: true,
    },
    {
      code: 'KeyI',
      type: 'Symbol',
      downEng: 'i',
      downRu: 'ш',
      letter: true,
    },
    {
      code: 'KeyO',
      type: 'Symbol',
      downEng: 'o',
      downRu: 'щ',
      letter: true,
    },
    {
      code: 'KeyP',
      type: 'Symbol',
      downEng: 'p',
      downRu: 'з',
      letter: true,
    },
    {
      code: 'BracketLeft',
      type: 'Symbol',
      upEng: '{',
      downEng: '[',
      downRu: 'х',
      upRu: 'Х',
    },
    {
      code: 'BracketRight',
      type: 'Symbol',
      downEng: ']',
      downRu: 'ъ',
      upEng: '}',
      upRu: 'Ъ',
    },
    {
      code: 'Backslash',
      type: 'Symbol',
      downEng: '\\',
      downRu: '\\',
      upEng: '|',
      upRu: '/',
    },
    {
      code: 'Delete',
      type: 'Function',
      down: 'Del',
    },
  ],
  [
    {
      code: 'CapsLock',
      type: 'Function',
      down: 'CapsLock',
      specialSize: 1,
    },
    {
      code: 'KeyA',
      type: 'Symbol',
      downEng: 'a',
      downRu: 'ф',
      letter: true,
    },
    {
      code: 'KeyS',
      type: 'Symbol',
      downEng: 's',
      downRu: 'ы',
      letter: true,
    },
    {
      code: 'KeyD',
      type: 'Symbol',
      downEng: 'd',
      downRu: 'в',
      letter: true,
    },
    {
      code: 'KeyF',
      type: 'Symbol',
      downEng: 'f',
      downRu: 'а',
      letter: true,
    },
    {
      code: 'KeyG',
      type: 'Symbol',
      downEng: 'g',
      downRu: 'п',
      letter: true,
    },
    {
      code: 'KeyH',
      type: 'Symbol',
      downEng: 'h',
      downRu: 'р',
      letter: true,
    },
    {
      code: 'KeyJ',
      type: 'Symbol',
      downEng: 'j',
      downRu: 'о',
      letter: true,
    },
    {
      code: 'KeyK',
      type: 'Symbol',
      downEng: 'k',
      downRu: 'л',
      letter: true,
    },
    {
      code: 'KeyL',
      type: 'Symbol',
      downEng: 'l',
      downRu: 'д',
      letter: true,
    },
    {
      code: 'Semicolon',
      type: 'Symbol',
      downEng: ';',
      downRu: 'ж',
      upEng: ':',
      upRu: 'Ж',
    },
    {
      code: 'Quote',
      type: 'Symbol',
      upEng: '\'',
      downEng: '\'',
      downRu: 'э',
      upRu: 'Э',
    },
    {
      code: 'Enter',
      type: 'Function',
      down: 'Enter',
      specialSize: 1,
    },
  ],
  [
    {
      code: 'ShiftLeft',
      type: 'Function',
      down: 'Shift',
      specialSize: 1,
    },
    {
      code: 'KeyZ',
      type: 'Symbol',
      downEng: 'z',
      downRu: 'я',
      letter: true,
    },
    {
      code: 'KeyX',
      type: 'Symbol',
      downEng: 'x',
      downRu: 'ч',
      letter: true,
    },
    {
      code: 'KeyC',
      type: 'Symbol',
      downEng: 'c',
      downRu: 'с',
      letter: true,
    },
    {
      code: 'KeyV',
      type: 'Symbol',
      downEng: 'v',
      downRu: 'м',
      letter: true,
    },
    {
      code: 'KeyB',
      type: 'Symbol',
      downEng: 'b',
      downRu: 'и',
      letter: true,
    },
    {
      code: 'KeyN',
      type: 'Symbol',
      downEng: 'n',
      downRu: 'т',
      letter: true,
    },
    {
      code: 'KeyM',
      type: 'Symbol',
      downEng: 'm',
      downRu: 'ь',
      letter: true,
    },
    {
      code: 'Comma',
      type: 'Symbol',
      downEng: ',',
      downRu: 'б',
      upEng: '<',
      upRu: 'Б',
    },
    {
      code: 'Period',
      type: 'Symbol',
      downEng: '.',
      downRu: 'ю',
      upEng: '>',
      upRu: 'Ю',
    },
    {
      code: 'Slash',
      type: 'Symbol',
      downEng: '/',
      downRu: '.',
      upEng: '?',
      upRu: ',',
    },
    {
      code: 'ArrowUp',
      type: 'Function',
      down: '↑',
    },
    {
      code: 'ShiftRight',
      type: 'Function',
      down: 'Shift',
      specialSize: 1,
    },
  ],
  [
    {
      code: 'ControlLeft',
      type: 'Function',
      down: 'Ctrl',
    },
    {
      code: 'MetaLeft',
      type: 'Function',
      down: 'Win',
    },
    {
      code: 'AltLeft',
      type: 'Function',
      down: 'Alt',
    },
    {
      code: 'Space',
      type: 'Function',
      down: '',
      specialSize: 2,
    },
    {
      code: 'AltRight',
      type: 'Function',
      down: 'Alt',
    },
    {
      code: 'ArrowLeft',
      type: 'Function',
      down: '←',
    },
    {
      code: 'ArrowDown',
      type: 'Function',
      down: '↓',
    },
    {
      code: 'ArrowRight',
      type: 'Function',
      down: '→',
    },
    {
      code: 'ControlRight',
      type: 'Function',
      down: 'Ctrl',
    },
  ],
];
export default keys;
